version: '3.9'

services:
  gateway:
    build: ./services/gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth
    environment:
      - JWT_SECRET=super_secret

  auth:
    build: ./services/auth
    ports:
      - "8082:8082"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
      - JWT_SECRET=super_secret
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=auth_user
      - POSTGRES_PASSWORD=auth_pass
      - POSTGRES_DB=auth_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
